ansible/ansible_tower_client_ruby

ansible_tower_client.gemspec
lib/ansible_tower_client/collection_methods.rb
spec/ad_hoc_command_spec.rb
spec/collection_methods_spec.rb
spec/factories/responses.rb
spec/group_spec.rb
spec/host_spec.rb
spec/inventory_spec.rb
spec/job_spec.rb
spec/job_template_spec.rb
spec/spec_helper.rb
spec/support/factory_helper.rb
spec/support/shared_examples/collection_methods.rb

Ensure collections are built with the correct type.
Fix lots of spec failures due to this change.
Add FactoryGirl and reduce duplication through factories and shared_examples

Spec cleanup

---

lib/ansible_tower_client/job_template.rb
spec/job_template_spec.rb

We currently return extra_vars as a raw string.
Survey_spec was returned as a JSON.parsed Hash.
The app is expecting to save a raw string - identical to extra_vars
This simply makes the two attributes more alike.

Return survey_spec as a string

---

lib/ansible_tower_client/job_template.rb
spec/factories/responses.rb
spec/job_template_spec.rb

1. Pass the post url with extra_vars into a block
2. Make a separate patch call to update the limit
3. Yield the original launch restful call
4. Ensure the limit is set back to what it originally was.

Added with_temporary_changes to handle updating limit

---

lib/ansible_tower_client/collection.rb
lib/ansible_tower_client/inventory.rb
spec/ad_hoc_command_spec.rb
spec/factories/responses.rb
spec/group_spec.rb
spec/host_spec.rb
spec/inventory_spec.rb
spec/job_spec.rb
spec/job_template_spec.rb
spec/support/shared_examples/collection_methods.rb

Extract the behavior of the Collection#all method
into find_all_by_url so we can use the same behavior
with any url passed in.
Collection#all now calls find_all_by_url.
by passing in klass.endpoint as an argument.

Create find_all_by_url method

---

lib/ansible_tower_client/collection.rb
lib/ansible_tower_client/group.rb
lib/ansible_tower_client/host.rb
lib/ansible_tower_client/inventory.rb
spec/support/shared_examples/collection_methods.rb

Rewrite collections to return lazy Enumerators instead of Arrays
Break out:
- response parsing
- result set parsing
- building objects out of results
- fetching pages
Merge #find_all_by_url and #collection_for after refactoring
Lazy Enumerators allow for quicker initial response since a page is only requested and its objects created when needed rather than fetching all pages at once then creating objects from each result.
Make 'klass' optional since it is only required for #find
Update Collection specs accordingly
- The old solution is only going to get slower as the amount of collection items increases
- Long initial delay before chained methods (collect, each) can start processing
- The old solution will fetch all records even if we only care about the first N
- `all` returns an …

Change Collection to use lazy enumerators

---

.rspec
ansible_tower_client.gemspec
spec/ad_hoc_command_spec.rb
spec/api_spec.rb
spec/connection_spec.rb
spec/group_spec.rb
spec/host_spec.rb
spec/inventory_source_spec.rb
spec/inventory_spec.rb
spec/inventory_update_spec.rb
spec/job_spec.rb
spec/job_template_spec.rb
spec/null_logger_spec.rb

Rails 5 isn't compatible with older rubies.
Upgrade more_core_extensions to provide `blank?`

Limit ActiveSupport version if Ruby version is less than 2.2.2

---

lib/ansible_tower_client/connection.rb

Fixes error:
unsupported media type "application/x-www-form-urlencoded" in request
https://bugzilla.redhat.com/show_bug.cgi?id=1348500

Ensure we always set content_type of "application/json"

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/exception.rb

Based on [these changes](https://github.com/ManageIQ/manageiq/pull/8947)
Attempt to JSON parse the error message and if it fails, return a generic message.  Rescue `Faraday::ConnectionFailed` and `Faraday::SSLError` and re-raise them first since they inherit from `Faraday::ConnectionError`.

Rescue client errors

---

Gemfile
ansible_tower_client.gemspec

Allow tests to run with the correct version of activesupport for their
ruby version.

Move activesupport hack to Gemfile.

---

lib/ansible_tower_client/api.rb

GET missing resource
```
[----] E, [2016-12-02T15:25:56.560087 #2118:100f108] ERROR -- : AnsibleTowerClient::Api Faraday::ResourceNotFound Not found.
```
With debug logging:
```
[----] D, [2016-12-02T15:26:13.107248 #2118:100f108] DEBUG -- : AnsibleTowerClient::Api Sending <get> with <["job_templates/1111111/"]>
[----] D, [2016-12-02T15:26:13.344309 #2118:100f108] DEBUG -- : AnsibleTowerClient::Api Faraday::ResourceNotFound {:status=>404,
:headers=>
{"date"=>"Fri, 02 Dec 2016 21:25:46 GMT",
"server"=>
"Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips mod_wsgi/3.4 Python/2.7.5",
"vary"=>"Accept,Cookie",
"allow"=>"GET, PUT, PATCH, DELETE, HEAD, OPTIONS",
"x-api-time"=>"0.031s",
"content-length"=>"23",
"connection"=>"close",
"content-type"=>"application/json"}, …
```

Provide better error logging for debugging

---

lib/ansible_tower_client/api.rb

When the API class receives a Faraday::ClientError with a nil
response, we simply bubble up that error to the caller
instead of modifying and repackaging it as a ConnectionError

raise the original client error if no response

---

lib/ansible_tower_client/base_model.rb
spec/ad_hoc_command_spec.rb
spec/group_spec.rb
spec/host_spec.rb
spec/inventory_source_spec.rb
spec/inventory_spec.rb
spec/job_spec.rb
spec/job_template_spec.rb
spec/job_template_v2_spec.rb
spec/support/shared_examples/crud_methods.rb

Opens create to all subclasses
The InventorySource class does not support POST's per the API
Overriding the self.create method to save the lookup

Add create method to the base_model

---

lib/ansible_tower_client/collection.rb
spec/support/shared_examples/collection_methods.rb

adds ability to pass down options to collections
```ruby
filter = {
:order_by      => 'timestamp',
:timestamp__gt => '2016-08-02T17:56:37.212874Z'
}
connection.api.activity_stream.all(filter)
```
see sorting, searching and filtering in the tower api docs https://docs.ansible.com/ansible-tower/3.0.1/html/towerapi
@miq-bot assign @syncrou

allow passing of GET options to .all in collections

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/base_models/activity_stream.rb
spec/activity_stream_spec.rb

also adds ability to pass down options to collections

add activity stream as an api method

---

lib/ansible_tower_client/base_model.rb
lib/ansible_tower_client/collection.rb
lib/ansible_tower_client/exception.rb

- Be more like ActiveRecord::Base
- Allow `create` to be called on an instance of AnsibleTowerClient::Collection

Add create to collection

---

.gitignore
Gemfile
ansible_tower_client.gemspec

If there is a development Gemfile called Gemfile.dev.rb
bundler will pull it in and include those gems
as development dependencies.

Allow for development Gemfile

---

lib/ansible_tower_client/base_models/project.rb
lib/ansible_tower_client/collection.rb
spec/support/shared_examples/collection_methods.rb

Playbooks are only available from a project.
This PR exposes `/playbooks` as a collection from said project.
The Tower API returns playbooks as an Array vs a Hash from POST, PUT, PATCH(able) endpoints.
The `parse_result_set` method was modified to handle each case appropriately while not breaking the existing lazy `Enumerator` behavior.
https://www.pivotaltracker.com/story/show/137293767
> Testing Notes
```
conn = AnsibleTowerClient::Connection.new(
:username => "username",
:password => "password",
:base_url => "https://dev-ansible-tower3.test.com/api/v1",
:verify_ssl => OpenSSL::SSL::VERIFY_NONE
)
proj = conn.api.projects.find <id>
proj.playbooks.first
```
```
conn = AnsibleTowerClient::Connection.new(
:username => "username",
:password => "password",
:base_url => …
```

Expose playbooks off of projects

---

lib/ansible_tower_client/base_model.rb
lib/ansible_tower_client/base_models/ad_hoc_command.rb
lib/ansible_tower_client/base_models/credential.rb
lib/ansible_tower_client/base_models/group.rb
lib/ansible_tower_client/base_models/host.rb
lib/ansible_tower_client/base_models/inventory.rb
lib/ansible_tower_client/base_models/inventory_source.rb
lib/ansible_tower_client/base_models/inventory_update.rb
lib/ansible_tower_client/base_models/job.rb
lib/ansible_tower_client/base_models/job_template.rb
lib/ansible_tower_client/base_models/project.rb
spec/activity_stream_spec.rb
spec/group_spec.rb
spec/host_spec.rb
spec/inventory_source_spec.rb
spec/inventory_spec.rb
spec/inventory_update_spec.rb
spec/job_spec.rb
spec/job_template_spec.rb
spec/job_template_v2_spec.rb
spec/project_spec.rb
spec/support/shared_examples/api_methods.rb

Pulling specific `self.endpoint` methods out of all the subclasses and standardize it from the `base_model`

Refactor endpoint

---

lib/ansible_tower_client/base_models/job_template.rb
lib/ansible_tower_client/exception.rb
lib/ansible_tower_client/middleware/raise_tower_error.rb
spec/middleware/raise_tower_error_spec.rb
spec/support/shared_examples/job_template.rb

Rescue UnlicensedFeatureError when trying to fetch survey_data
https://bugzilla.redhat.com/show_bug.cgi?id=1370251

Raise UnlicensedFeatureError when we receive a HTTP 402

---

lib/ansible_tower_client/api.rb
spec/api_spec.rb

By default Ansible Tower assumes that it is always at /api/v1/.
That may not always be the case, so this change allows us to specify an
alternative when initializing the connection.

Allow for alternative resource paths

---

lib/ansible_tower_client/api.rb
lib/ansible_tower_client/exception.rb
lib/ansible_tower_client/middleware/raise_tower_error.rb
spec/middleware/raise_tower_error_spec.rb

All client errors should derive from AnsibleTowerClient::ClientError

---

lib/ansible_tower_client/api.rb
lib/ansible_tower_client/middleware/raise_tower_error.rb
spec/middleware/raise_tower_error_spec.rb

Log the error from the middleware to avoid rerescuing AnsibleTowerClient errors in Api class.
This will log:
```
[----] D, [2017-02-22T17:47:41.987732 #17232:c27108] DEBUG -- : AnsibleTowerClient::Middleware::RaiseTowerError Response:
#<struct Faraday::Env
method=:post,
body=
"{\"inventory\":[\"Job Template 'inventory' is missing or undefined.\"]}",
url=#<URI::HTTPS https://10.x.x.x/api/v1/job_templates/7/launch/>,
request=
#<struct Faraday::RequestOptions
params_encoder=nil,
proxy=nil,
bind=nil,
timeout=nil,
open_timeout=nil,
boundary=nil,
oauth=nil>,
request_headers=
{"Authorization"=>"Basic YWRtaW46cGFzc3dvcmQxMjM=",
"User-Agent"=>"Faraday v0.9.2",
"Content-Type"=>"application/json"},
ssl=
#<struct Faraday::SSLOptions
verify=false,
ca_file=nil,
ca_path=nil,
verify_mode=nil, …
```

Fix error logging after changing error response classes

---

lib/ansible_tower_client/base_model.rb
lib/ansible_tower_client/base_models/job_template.rb
spec/job_template_spec.rb

the `HashModel`  rewrites integer based attributes into attribute_id. This PR rewrites the raw values returned from
an API response into the correct '_id' style
https://www.pivotaltracker.com/story/show/140521307

Override RAW attributes

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/base_models/job.rb
lib/ansible_tower_client/base_models/job_event.rb
spec/factories/responses.rb
spec/job_event_spec.rb
spec/job_spec.rb

1. Expose `job_plays` off of `AnsibleTowerClient::Job`
2. Add `job_events` as a Collection
3. Add `AnsibleTowerClient::JobEvent` 
Testing Notes
1. Lookup a Job
`job = connection.api.jobs.find n`
2. Call job_plays off of said job
`job.job_plays.first`
3. Returned object will be a `AnsibleTowerClient::JobEvent`

Expose plays, JobEvent

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/base_models/organization.rb
spec/organization_spec.rb

This will allow us to add and remove organizations using this API client.
https://www.pivotaltracker.com/story/show/140098929
@syncrou @bdunne please review

Add the Organization model

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/base_model.rb
lib/ansible_tower_client/base_models/host.rb
lib/ansible_tower_client/base_models/inventory.rb
lib/ansible_tower_client/base_models/job.rb
lib/ansible_tower_client/base_models/job_play.rb
lib/ansible_tower_client/collection.rb
spec/factories/responses.rb
spec/job_event_spec.rb
spec/job_play_spec.rb
spec/job_spec.rb

The Tower API returns `job_event` summary types when querying the `/job_plays/` endpoint. 
In this PR we create a mechanism that allows us to force a type (in this case `AnsibleTowerClient::JobPlay` when we don't want to use the `type` column passed back by the Tower provider.

Override type when appropriate

---

lib/ansible_tower_client/base_models/job.rb
spec/job_spec.rb

API already supports differently formatted stdout.

Allow formatted stdout, default to plain text

---

lib/ansible_tower_client/collection.rb
spec/collection_spec.rb

Options should be cleared on subsequent calls within the loop because they are already included in the next_page url.
However each time the enumerator is enumerated it calls the initial get and needs the options passed in.

Allow collection enumerator to be enumerated multiple times

---

spec/activity_stream_spec.rb

Depends on https://github.com/ansible/ansible_tower_client_ruby/pull/88
None of these `let`s are used in the specs for this model.  Removing them to avoid confusion.

Remove extra cruft in activity_stream_spec.rb

---

lib/ansible_tower_client/base_models/credential.rb
spec/credential_spec.rb

in the same spirit as https://github.com/ansible/ansible_tower_client_ruby/pull/75
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1444398 in manageiq
and better than https://github.com/ManageIQ/manageiq/pull/14863

translate organization_id to organization

---

spec/ad_hoc_command_spec.rb
spec/api_spec.rb
spec/credential_spec.rb
spec/group_spec.rb
spec/host_spec.rb
spec/inventory_source_spec.rb
spec/inventory_spec.rb
spec/job_event_spec.rb
spec/job_spec.rb
spec/job_template_spec.rb
spec/job_template_v2_spec.rb
spec/organization_spec.rb
spec/project_spec.rb
spec/support/mock_api.rb
spec/support/mock_api/ad_hoc_command.rb
spec/support/mock_api/config.rb
spec/support/mock_api/credential.rb
spec/support/mock_api/group.rb
spec/support/mock_api/host.rb
spec/support/mock_api/inventory.rb
spec/support/mock_api/inventory_source.rb
spec/support/mock_api/job.rb
spec/support/mock_api/job_template.rb
spec/support/mock_api/me.rb
spec/support/mock_api/organization.rb
spec/support/mock_api/project.rb
spec/support/shared_examples/job_template.rb

@syncrou I think it's about time we start testing with real data.  There's more coming, but in this PR I covered the root collection classes.
I know there is some duplication and the `get` method needs to be smarter, but I wanted to keep this relatively small so it isn't impossible to review.  Let me know what you think.
I even found and fixed a bug in a spec which proves that the previous mocking wasn't adding much value for the `#initialize` tests.

Add MockApi for testing

---

lib/ansible_tower_client/base_model.rb
spec/support/shared_examples/crud_methods.rb

This is to fix https://bugzilla.redhat.com/show_bug.cgi?id=1445995
When caller passes in attributes that client doesn't know, even though Tower succeed in the call, client is blown up.
@miq-bot add_labels wip, bug

Check before update attribute of basemodel

---

ansible_tower_client.gemspec

See https://github.com/lostisland/faraday/pull/714 for more details
@syncrou Please review.
~~This will conflict with manageiq-api-client~~ Fixed by https://github.com/ManageIQ/manageiq-api-client/pull/71

Upgrade Faraday to minimum of v0.13 for IPv6 support

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/base_models/system_job.rb
lib/ansible_tower_client/base_models/system_job_template.rb
spec/factories/responses.rb
spec/support/mock_api/system_job_template.rb
spec/system_job_template_spec.rb

This will allow us to trigger a system job template manually and return the created system job.
@bdunne please review
https://bugzilla.redhat.com/show_bug.cgi?id=1560478

Add SystemJobTemplate#launch and the SystemJob class

---

ansible_tower_client.gemspec

This reverts commit 7e82aa8bee9bab0d4a8ca0f58cb5c4a38f95773d.
Reverting until the rest of ManageIQ is able to upgrade. cc @carbonin

Revert "Upgrade Faraday to minimum of v0.13 for IPv6 support"

---

CHANGELOG.md
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/base_models/project.rb
lib/ansible_tower_client/logging.rb
lib/ansible_tower_client/middleware/raise_tower_error.rb
spec/api_spec.rb
spec/factories/responses.rb
spec/job_template_v2_spec.rb
spec/middleware/raise_tower_error_spec.rb
spec/project_spec.rb

Add method to `Project` model that fetches stdout capture of its last update job. It uses `'related'` property of the Project. Returns `nil` if there is no update job for the Project.
Fetching and presenting this information is a workaround for cloning repositories from HTTPS servers with untrusted SSL certificates. Tower API does not offer an option to disable SSL check, so with the stdout user can at least see, why the cloning actually failed.
Alongside fix some subtle bugs in the `Api` class:
* Non-JSON responses were not logged correctly. This bug was hidden because with the default log level `debug` logs are skipped.
* `Faraday` was not available in the `Api` class, resulting it raising `LoadError` while catching `Faraday::*` exception. …

Add project last update stdout

---

spec/collection_spec.rb

In tests we weren't setting the version number for our mock api and this error was noticed when upgrading from Gem v2.7.6 to v2.7.7.
@bzwei @syncrou Please review, fixes test failures in https://github.com/ansible/ansible_tower_client_ruby/pull/105#issuecomment-393524937 since Travis is running with Gem v2.7.7

Gem::Version.new(nil) raises ArgumentError: Malformed version number string

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/base_models/workflow_job.rb
lib/ansible_tower_client/base_models/workflow_job_template.rb
lib/ansible_tower_client/base_models/workflow_job_template_node.rb
spec/collection_spec.rb
spec/factories/responses.rb
spec/support/mock_api.rb
spec/support/mock_api/workflow_job_template.rb
spec/support/mock_api/workflow_job_template_node.rb
spec/workflow_job_template_node_spec.rb
spec/workflow_job_template_spec.rb

https://bugzilla.redhat.com/show_bug.cgi?id=1468339
Part of https://github.com/ManageIQ/manageiq/issues/17441

workflow_job_template and workflow_job_template_node

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/connection.rb
lib/ansible_tower_client/v2/credential_v2.rb
spec/ad_hoc_command_spec.rb
spec/api_spec.rb
spec/collection_spec.rb
spec/connection_spec.rb
spec/credential_spec.rb
spec/group_spec.rb
spec/host_spec.rb
spec/inventory_source_spec.rb
spec/inventory_spec.rb
spec/job_event_spec.rb
spec/job_spec.rb
spec/job_template_spec.rb
spec/job_template_v2_spec.rb
spec/organization_spec.rb
spec/project_spec.rb
spec/support/mock_api.rb
spec/support/mock_api/v2/credential.rb
spec/system_job_template_spec.rb
spec/v2/credential_spec.rb
spec/workflow_job_template_node_spec.rb
spec/workflow_job_template_spec.rb

With this commit we allow user to quickly switch between v1 and v2 per API call:
```ruby
client = AnsibleTowerClient::Connection.new(
:base_url   => 'http://localhost:54321',
:username   => 'admin',
:password   => 'password'
)
client.api(:version => 1).credentials.all.each do |c|
pp c
end
client.api(:version => 2).credentials.all.each do |c|
pp c
end
```
This way migrating ManageIQ to use v2 will be easier because we can migrate API call by API call.
Related issue: https://github.com/ManageIQ/manageiq-providers-ansible_tower/issues/96

Support both API v1 and v2 at the same time

---

lib/ansible_tower_client/connection.rb
spec/connection_spec.rb

Set the faraday response logger when creating a new Faraday object.
Allow the logger to be set as an option to the AnsibleTowerClient::Connection or fall back to the AnsibleTowerClient.logger.

Set the faraday logger when creating connection

---

lib/ansible_tower_client.rb
lib/ansible_tower_client/api.rb
lib/ansible_tower_client/exception.rb
lib/ansible_tower_client/v2/credential_type_v2.rb
spec/factories/responses.rb
spec/support/mock_api.rb
spec/support/mock_api/v2/credential_type.rb
spec/v2/credential_type_spec.rb

With this commit we add a new API call which is only supported on API v2:
```
client.api.credential_types
```
It returns a list of all credential types as well as offer CRUD for them.

API call for credential types

---

lib/ansible_tower_client/hash_model.rb
spec/base_model_spec.rb

Any key in the original hash is used in the base model for two purpose:
1. underscore version is used as a method
2. camelized version is used as a class
Either case only accepts alphabetic letters, numbers, and _. All other characters are now replaced.
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1583844

Replace all characters that cannot be used as method or class name

---

lib/ansible_tower_client/connection.rb

Connection logic currently utilizes the OpenSSL module directly but
doesn't require it, throwing an error under certain circumstances.
This is easily reproduced with the following code:
```
require 'ansible_tower_client'
ansible = AnsibleTowerClient::Connection.new(username: "admin",
password: "tower-password",
base_url: "https://tower-address.com",
verify_ssl: true)
inventories = ansible.api.inventories
inventories.all.each { |inventory| puts inventory }
```
And creates the following error, as it searches for `OpenSSL` in the
context of the current module, which doesn't exist (but is a
part of faraday it seems).
```
Traceback (most recent call last):
2: from ansible_reproducer.rb:3:in `<main>'
1: from ansible_reproducer.rb:3:in `new' …
```

Require 'openssl' in connections

---

lib/ansible_tower_client/base_models/project_update.rb
spec/project_update_spec.rb

Fixing https://github.com/ManageIQ/manageiq-automation_engine/issues/261
Related https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/140

Tower 3.3 removed result_stdout field from project_update

---

lib/ansible_tower_client/api.rb
lib/ansible_tower_client/collection.rb
lib/ansible_tower_client/middleware/raise_tower_error.rb
spec/collection_spec.rb
spec/middleware/raise_tower_error_spec.rb
spec/support/mock_api.rb

**avoid redundant redirects**
Currently, base resource paths got requested without trailing slashes in addresses.
It leads so such lines in the logs:
```
INFO -- : get https://example.com/api/v2/config
INFO -- Status: 301
INFO -- : get https://example.com/api/v2/config/
INFO -- Status: 200
INFO -- : get https://example.com/api/v2/inventories
INFO -- Status: 301
INFO -- : get https://example.com/api/v2/inventories/
INFO -- Status: 200
```
This commit eliminates useless redirect hops.
**unhide url of not found resource**
Ease `404`-related errors debugging.

little improvements

---

lib/ansible_tower_client/collection.rb
spec/collection_spec.rb

Related project updates perform a find with an id with a trailing slash,
such as 'project_updates/233/'.  Previously, we'd append another
trailing slash and it would be up to the underlying faraday code to fix it.
On ruby 2.5.x, faraday would receive two trailing slashes and not fix
it.  On ruby 2.4.x, we'd send two trailing slashes to faraday
but it would perform the get with only a single trailing slash.
It's unclear what changed in ruby 2.4 vs. 2.5 to behave differently with the same
faraday and other gems, but it's better to ensure we don't try to send an invalid
URI to faraday.

[ruby 2.5] Ensure no double trailing slash

---

lib/ansible_tower_client/api.rb

this is a follow-up for https://github.com/ansible/ansible_tower_client_ruby/pull/124
found one more place with redirecting url

avoid redundant redirects

---

.travis.yml
ansible_tower_client.gemspec
spec/factories/responses.rb
spec/spec_helper.rb

This updates the gemspec by updating the bundler and rake versions, removes some unnecessary load path mangling, and gets rid of the `require_paths` specification since 'lib' is already the default.
Edit: also realized factory_girl needed to be updated to factory_bot.

Update bundler, rake, remove unnecessary load path mangling

---

lib/ansible_tower_client/base_models/workflow_job_node.rb
spec/workflow_job_node_spec.rb

Add logic to filter out workflow job node that is for inventory sync or project sync.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1698837

Add logic to filter out workflow job node that is for sync

---

lib/ansible_tower_client/base_models/credential.rb
spec/credential_spec.rb

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1740860

prevent undefined vault_password error

---

lib/ansible_tower_client/connection.rb

Accept request options to be sent to faraday so that things like open_timeout can be given.

Allow request options to be passed to Faraday so that open_timeout can be set

---

lib/ansible_tower_client/api.rb

Previous versions of this gem requested /config/ to avoid redundant redirects (added in https://github.com/ansible/ansible_tower_client_ruby/pull/124).  Now it is requesting /config which is causing vcr breakages after https://github.com/ansible/ansible_tower_client_ruby/pull/137 changed [this](https://github.com/ansible/ansible_tower_client_ruby/pull/137/files#diff-6dc31f2bbd85dcda6dd9f0d93fa6e045R15)
Failure on manageiq hammer on first run after v0.21.0 was released https://travis-ci.org/ManageIQ/manageiq/builds/651202354#L1149

Fix specs with VCRs recorded on previous versions

---

Gemfile

Removing since we're no longer concerned about Ruby < 2.2.2

This never worked as intended, it was evaluated at build time.

---

ansible_tower_client.gemspec

more core extensions is now on 4.1.0 and I was wondering if we might be able to update. 
no particular reason, just update for update's sake
here's what's included:
https://github.com/ManageIQ/more_core_extensions/compare/179bf40..e5b4501
- Added Ruby 2.7 support [[#79](https://github.com/ManageIQ/more_core_extensions/pull/79)]
- Added Process#pause, Process#resume, and Process#alive? [[#73](https://github.com/ManageIQ/more_core_extensions/pull/73)]
array added * `#compact_map` - Collect non-nil results from the block
array added `#tabular_sort` - Sorts an Array of Hashes by specific columns
hierarchy added `#descendant_get` - Returns the descendant with a given name
the two breaking changes:
- **BREAKING**: Moved Object#descendant_get to Class#descendant_get …

bump more core extensions
